# Generated by Django 4.1.7 on 2023-03-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_shop_user_shop_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='price',
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='shopping.cart'),
        ),
    ]
