# Generated by Django 4.1.7 on 2023-03-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_alter_productreview_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='productreview',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
