# Generated by Django 4.1.7 on 2023-03-25 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_rename_created_at_shopreview_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='shopping.shop'),
        ),
    ]
