# Generated by Django 4.1.7 on 2023-03-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_alter_category_description_alter_like_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='cartdetail',
            unique_together={('product', 'cart')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('product', 'order')},
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='cartdetail',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='sizes',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='colors',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='shopping.color'),
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='sizes',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='shopping.size'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='colors',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='shopping.color'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='sizes',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='shopping.size'),
        ),
    ]
