# Generated by Django 4.1.7 on 2023-03-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='xs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(default='xs', max_length=10, null=True),
        ),
    ]
