# Generated by Django 4.1.7 on 2023-03-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_shop_address_shop_email_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(default='xs', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(default='xs', max_length=10),
        ),
    ]
